#!/bin/bash
#
# Typical job script to run a 1 CPU, 1 GPU batch job in the production queue
# 
#PBS -q production
#PBS -N test_job
#PBS -l select=1:ncpus=1:ngpus=1
#PBS -l place=free
#PBS -V

# Find out which compute node the job is using
hostname

# Change to working directory
cd $PBS_O_WORKDIR
if [ ! -d "/scratch/shmuel.pfeiffer/BDiF2015-Sam-Pfeiffer/AssignmentB" ];then
   mkdir -p /scratch/shmuel.pfeiffer/BDiF2015-Sam-Pfeiffer/AssignmentB
fi

# Run my GPU job on a single node using 1 CPU and 1 GPU.
/scratch/shmuel.pfeiffer/BDiF2015-Sam-Pfeiffer/AssignmentB/test.out >  test.txt 2>&1